### PR TITLE
fixes for Django 1.9

### PR DESCRIPTION
**Pull request by PetrDlouhy**
Django mass admin made working in Django 1.9 with appropriate tests

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
The tests are working, but the edition not. Wait for the fix.

**Comment by PetrDlouhy** [comment]
Now it's fixed and ready to pull.

**Comment by bufke** [comment]
Thanks!

**Comment by bufke** [comment]
2.6 release is out - let me know if you have any trouble.

**Pull request merged**
