### PR TITLE
update Django up to 4.2 to the testing matrix

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@bufke I have added new versions of Django to the testing matrix. Everything seems to work OK, but the last release of this application seems to be outdated and missing several commits from `master` branch.

I have already rights to this repository to prepare the changes needed to make a release, but I don't have access to the PyPI repository.
Would you like to make the release yourself or would you give me the rights?

**Comment by bufke** [comment]
I can grant you access @PetrDlouhy, what's your pypi.org username?

**Comment by PetrDlouhy** [comment]
@bufke Thank you very much. My username is `petr.dlouhy`.

**Comment by PetrDlouhy** [comment]
@bufke Thank you very much.

**Pull request merged**
