### PR TITLE
Updated README.md for Django 1.9+

### PR DESCRIPTION
**Pull request by namanshenoy**
Added code to get django-mass-edit working on Django 1.9+

### CODE REVIEW

**Comment by bufke** [comment]
Why is this method better than? https://github.com/burke-software/django-mass-edit/blob/32e6dbe1255e6c2ed04bfbfc54d20467003ebdec/massadmin/__init__.py#L31

Does that init thing no longer work from a Django change?

**Comment by namanshenoy** [comment]
Yeah it didn't work when I tried.
Might have something to do with template loaders.

**Comment by bufke** [comment]
I'd rather have the action just magically appear. Maybe try to figure out why it's not working for you and see if there is a alternative.

**Comment by namanshenoy** [comment]
Sounds good! Will make another PR, but for now I think the readme change is
necessary because it does not work out of the box at all with the new
django changes

**Comment by namanshenoy** [comment]
Besides, you need to add the urls anyway, so adding another line to the same file isn't really any different

**Comment by bufke** [comment]
I'm against adding speculation on a project's readme. If you find a way to make it "just work" or a specific reason on why the "just works" method isn't working for you we could add it to the readme. For that I'd like to see documentation proving that Django does not allow apps adding admin actions automatically.

If I had to guess - we probably just need to move the logic to somewhere like [here](https://docs.djangoproject.com/en/1.11/ref/applications/#for-application-authors).

**Pull request closed without merging**
