### PR TITLE
FIX: Crashes for models that have change_form_template set

### PR DESCRIPTION
**Pull request by danialmalik**
## Description

**Related Issue**: https://github.com/burke-software/django-mass-edit/issues/83

`change_form_template` is not supported by `MassAdmin` right now. If any model admin has this value set, the app crashes on the mass edit page.

Since the change form and mass edit for serve two different purposes, it makes sense to separate the variable that can be used to override their templates.

#### To reproduce
- Implement a model admin
- Create a new admin template for `change_form_template`. you can leave the template empty with just `{% extends "admin/change_form.html" %}` in the first line.
- Try to use bulk edit on this model's objects.

#### Expected behavior
- You get the mass edit form

#### Current behavior
- App crashes with errors related to missing context values.

### CODE REVIEW

**Comment by danialmalik** [comment]
@PetrDlouhy  could you please have a look? Thanks

**Comment by PetrDlouhy** [comment]
@danialmalik Nice fix. Could you please add the `change_form_temlate` to the tests and verify, that it fails without your fix? And also, can you please mention the new `mass_change_form_template` option somewhere in docs?

I will try to make the tests running again through Github actions in the meantime.

**Comment by PetrDlouhy** [comment]
@danialmalik Now I have make the tests working again through GitHub actions. Could you please add the test for your case and rebase to current master?

**Comment by danialmalik** [comment]
@PetrDlouhy please have a look now

**Comment by PetrDlouhy** [comment]
@danialmalik Very nice. Thank you very much.

**Pull request merged**
